### ISSUE TITLE
cmd/tsuru-admin: platform-add wrong behavior with api timeout when using load-balancer

### ISSUE THREAD

**Issue by morpheu** [tsuru/tsuru#1140]
When using tsuru api behind a load-balancer with low timeout (aroung 60 sec), platform-add could lead to a timeout failure and apparently the platform will not be added. As side effect, when running platform-list, the failure platform will be listed but the image generated on process was not pushed to private register.

**Comment by tarsisazevedo** [comment]
We tested it and this not happening. If connection between client and tsuru api was lost the build continues and the image is pushed (tested at amazon and locally).
This error may be due to connection loss between tsuru api and docker. 
We'll change tsuru to not register the platform in database before image ready, and failed platform won't appear in `tsuru platform-list`
