### ISSUE TITLE
After detach from `tsuru app-shell` the API returns an error  

### ISSUE THREAD

**Issue by robsonpeixoto** [tsuru/tsuru#1173]
To see the error I need to active the tsuru server `debug` configuration.

How to replicate:
```
tsuru app-shell -a your-app
exit
```
or
```
tsuru app-shell -a your-app
<CTRL+D>
```

log:
```
2015/04/17 13:54:29 ERROR: error in docker node "http://10.37.255.50:2375": API error (500): bad file descriptor
```

**Comment by fsouza** [comment]
Hi @robsonpeixoto, thanks for reporting! This is already fixed at master. The issue is that we called ``exec start`` in the API, and then resize the TTY of the exec, but ``exec start`` returns when the exec is no longer alive, so calling resize on a exec that exited results in "bad file descriptor".

tsuru-server 0.11 will include the fix.
