### ISSUE TITLE
docs: readthedocs "latest" version appears to be behind

### ISSUE THREAD

**Issue by dcarley** [tsuru/tsuru#1193]
The "latest" version of the docs appears to be older than "stable".

Stable contains the text about MongoDB and Redis from tsuru/tsuru#1117:
- http://docs.tsuru.io/en/stable/contributing/index.html#running-the-tests

Latest doesn't:
- http://docs.tsuru.io/en/latest/contributing/index.html#running-the-tests

**Comment by fsouza** [comment]
Hi @dcarley, this is a bug with Read the Docs that do not detect the new tags right away, so we need to wait some time before pointing latest to the new tag (stable works automatically, that's why we're referring to it now in our links).

I've just rebuilt the latest version to match 0.11.0 docs: 

Thanks for reporting it!

**Comment by dcarley** [comment]
Makes sense, thanks.
