### ISSUE TITLE
Restart policy when using container healing

### ISSUE THREAD

**Issue by dcarley** [tsuru/tsuru#1231]
We are using [container healing](http://docs.tsuru.io/en/stable/reference/config.html#docker-healing-heal-containers-timeout) and have experienced an issue when a Docker daemon or host is shutdown or rebooted for a short period of time that new containers are correctly scheduled on other hosts, but when the old host comes back up the old containers are also started and effectively orphaned.

Do you think it makes sense to disable the restart policy (from #888 and #889) when using container healing and let Tsuru take care of everything?

**Comment by cezarsa** [comment]
This will be taken care of in 0.12.0 as the big-sibling container already remove units that aren't registered in tsuru anymore.
One advantage of having the restart policy set is that for short failures (e.g. restarting the docker daemon) it will bring the containers back faster than the healing process would be able to detect and fix the failure.

**Comment by saliceti** [comment]
@cezarsa What is a *big-sibling* container?

**Comment by cezarsa** [comment]
@saliceti Yeah, that's it. We're still working on this documentation and it's expected to improve before we release 0.12.0. Also, it's part of the initiative started in #1136, because of it application containers will be a lot cheaper. We are working on a seamless migration from one model to the other, bs containers will be started automatically and older containers will remain working.

**Comment by fsouza** [comment]
Since this is not going to happen in the 0.12 release, I'm closing this issue.

@dcarley thanks for opening it!
