### ISSUE TITLE
Containers rebalance ignore containers on removed nodes

### ISSUE THREAD

**Issue by morpheu** [tsuru/tsuru#1246]
If one node removed from nodes list that still have running containers and a containers rebalance command is issued, containers belong to removed node will not be moved to a valid one

**Comment by cezarsa** [comment]
Not actually a bug. Running simply `tsuru-admin containers-rebalance` would rebalance containers from removed nodes to other existing nodes.

However, if after removing a node with `pool=mypoolname` we run a rebalance filtering by this same pool (`tsuru-admin containers-rebalance -f pool=mypoolname`) containers from the removed node will **not** be rebalanced. This happens because the the filter will only consider containers from nodes matching it, since the node was removed its containers won't be selected for rebalance.

Two things I think can be done to improve this behavior:

1. Add an option to the `containers-rebalance` command to make it rebalance only containers from nodes that were removed.

2. Add a new option to `docker-node-update`, something like `--disable` to completely disable a node while keeping it in the pool. This would cause rebalance command to consider containers in this node but they would all be redistributed in the pool.

I think both options should be implemented
