### ISSUE TITLE
tsuru-client: app-shell is not working when the http port is not explicit on tsuru target

### ISSUE THREAD

**Issue by andrewsmedina** [tsuru/tsuru#1262]
$ tsuru target-list | grep "*"
    * tsuru (mytsuru.com)

    $ tsuru app-shell -a dashboard
    Error: websocket.Dial ws://mytsuru.com/apps/dashboard/shell?height=24&term=xterm-256color&width=110: dial tcp: missing port in address mytsuru.com

    $ tsuru target-add newtsuru mytsuru.com:80 -s
    New target newtsuru -> mysturu.com:80 added to target list and defined as the current target

    $ tsuru app-shell -a dashboard
    ubuntu@a24ec5914aac:/$

**Comment by fsouza** [comment]
Can you provide more information on your environment?

It works here:

```
% tsuru target-list
  ...
* mytarget (tsuru.company.com)
  ...
% tsuru app-shell -a xxx-test
ubuntu@1ff727eab0c5:/$
```

How did you install tsuru?

**Comment by andrewsmedina** [comment]
$ tsuru version
    tsuru version 0.17.0

    $ tsurud version
    tsurud version 0.12.0.

**Comment by fsouza** [comment]
This error message comes from ``net.Dial``, but we don't call ``net.Dial`` directly. So, it's likely to be a bug in the websocket library, probably because you have an old version of it.

Here's the explicit part in the code where they handle implicit ports: https://github.com/golang/net/blob/master/websocket/client.go#L67-L79 (according to golang/net@5058c78c3627b31e484a81463acd51c7cecc06f3, this code has been written in December 2014 and committed in January 2015).

If this is your case, running ``godep restore`` before building the client should fix the issue.

**Comment by andrewsmedina** [comment]
I was using godep restore, but my version of websocket was from code.google. so the godep was not getting update to the right version.

thanks
