### ISSUE TITLE
Add parameter to app-list to display only app name

### ISSUE THREAD

**Issue by cezarsa** [tsuru/tsuru#1269]
Something like `tsuru app-list -q` similar to `docker ps -q`. This will make it easier create scripts using the client.

**Comment by dcarley** [comment]
I've found myself needing to parse the output of various sub-commands but struggled because of:
- column headers (e.g. `tsuru app-list | awk '{print $2}'` contains `Application`)
- ASCII tables (e.g. `tsuru app-list | awk '{print $2}'` contains empty lines)
- wrapped lines within a row (e.g. `Metadata` column in `tsuru-admin docker-node-list`)

I wonder if a generic solution would be to introduce a CLI flag for all sub-commands that replaces the ASCII table with single-row tab-delimited output? And/or default to that behaviour if the output is not a TTY (e.g. pipe)?
