### ISSUE TITLE
Extra units on applications

### ISSUE THREAD

**Issue by fsouza** [tsuru/tsuru#1407]
This is an old bug of tsuru: whenever launching a new unit, we insert a container with an empty ID in the database that later gets updated. The process may run too long, or the API process may die in the middle of the process. When this happens, the app remains locked. `tsuru-admin app-unlock` can easily solve this issue, but if the user deploys or restarts the application, she/he is going to get an extra container.

I'd like to suggest that we ignore containers with blank ids when running the pipeline that replaces units. We should also figure the ideal moment for removing containers with a blank id from the database (the best moment is probably when we're inserting a new one, so each app can have only one container with no id in the database).

I can work on that if everyone agrees on a solution.

**Comment by andrewsmedina** [comment]
I'm +1 for fix the extra units problem. 

Ignore empty containers will avoid the extra units problem. But I believe that removing empty containers in `insertEmptyContainerInDB` is not a simple task because this method is called concurrently on start containers.

a disclaimer: unlock applications that deploy takes too long can cause another problems. a possible fix is to implement a way to cancel/stop deploys.

**Comment by fsouza** [comment]
@andrewsmedina the issue is not only long-running deployments. If the API process dies (because OOM errors, for example), I may end-up with an outstanding lock and a container with an empty id.

**Comment by andrewsmedina** [comment]
I know that this issue is not only with long running deployments. This is the reason that I'm +1 for this issue :)

I have added the disclaimer about long running deployments, because some people can use unlock in this case thinking that is a good solution, but in almost of the cases isn't.
