### ISSUE TITLE
docker-node-add w/ ec2 returns 'pool is required' when pool is given already

### ISSUE THREAD

**Issue by morpheyesh** [tsuru/tsuru#1431]
I run this 

`tsuru-admin docker-node-add iaas=ec2 type=m3.medium image=ami-blah region=us-east-1 pool=team1 keyName=someec2 template=aws-1 `

I get this: `Error: Pool is required`
Pool does gets passed in, the issue is with the tsurud api server. 

```
//pool is present in the metadata though
	pool := params.Metadata["pool"] //this fails
	if pool == "" {
		return &errors.HTTP{Code: http.StatusBadRequest, Message: "pool is required"}
	}
```

I hardcode pool in tsurud to test it, I then get this: `Error: the parameter "imageid" is required`

**Comment by morpheyesh** [comment]
@fsouza @tarsisazevedo  Anything?

**Comment by fsouza** [comment]
@morpheyesh I'm sorry, I had some issues locally and wasn't able to work on that. I am definitely going to investigate this issue today. Thanks for your patience.

**Comment by cezarsa** [comment]
This issue happens because https://github.com/tsuru/tsuru/blob/633d8e01e74d8d4fb80443da1eea74a1ccd91dbf/provision/docker/handlers.go#L242 is expanding the template and overriding all `params.Metadata` with the template contents instead of merging them (as was done previously when the iaas package was responsible for merging the template parameters). We'll fix this for 1.1.

@morpheyesh One workaround for now is not using the `template=` when adding a new node and instead passing all template parameters you want to use directly to the `docker-node-add` call.

**Comment by fsouza** [comment]
@cezarsa cool, thanks for that information!

**Comment by morpheyesh** [comment]
@cezarsa cool man! thanks!
