### ISSUE TITLE
IaaS support: Proxmox and OpenNebula

### ISSUE THREAD

**Issue by guestisp** [tsuru/tsuru#1466]
I'm not a Go programmer and both are too hard for me to develop.

Can someone implement ProxMox & OpenNebula APIs for integration in Tsuru as IaaS management ?

**Comment by guestisp** [comment]
Here there is something usefull for Proxmox: https://github.com/joernott/go-proxmox

**Comment by gwmoura** [comment]
@guestisp on this project exists just the method CreateQemuVM, is only this you need for the proxmox?

**Comment by guestisp** [comment]
I don't know, i'm still waiting for some test hardware to use with Proxmox.

Where did you find the method `CreateQemuVM`  ?

**Comment by guestisp** [comment]
Just for reference, proxmox api docs is here: http://pve.proxmox.com/pve-docs/api-viewer/

**Comment by guestisp** [comment]
For opennebula there is a Go client here: https://github.com/megamsys/opennebula-go

**Comment by guestisp** [comment]
I have a working Proxmox cluster if you need some tests

**Comment by gwmoura** [comment]
@guestisp I'm sorry for delay, I want create add IaaS support for google cloud platform, I am studying how do it, it's not a promise, but I'm gonna try help you, I need conciliate work and open source :smile:

**Comment by andrestc** [comment]
Hi @gwmoura, @guestisp 

We are currently working on a [docker machine](https://github.com/docker/machine) based iaas(#1223). Docker machine has several drivers that provide support the iaas's (including google cloud platform). We are also going to support docker machine 3rd party drivers, which means we can use the [open nebula](https://github.com/OpenNebula/docker-machine-opennebula) one.

Instead of creating new iaas implementations we should try the docker machine iaas with their drivers, report issues and check if we can improve our implementation or their drivers (since they are also open source).

I'll be pushing a WIP version soon (and create issues of what its missing). Would be good to get some feedback on it.

**Comment by andrestc** [comment]
Since docker-machine support is pretty stable, we recommend new iaas to be ran as docker-machine drivers. We have no plans to add new iaas' to tsuru itself and we plan on moving our own implementations to docker-machine drivers.

**Comment by guestisp** [comment]
I understand, but native integration is easier to use for users and doesn't require an additional abstraction level to maange in case of issues.

OpenNebula is one of the most used private cloud software out there, like OpenStack, native support would be great, much more than DigitalOcean, IMHO.

DigitalOcean is a VPS provider, that could be used via Docker Machine, but full-iaas like OpenNebula or OpenStack should be native in tsuru, I think.
