### ISSUE TITLE
Failed to connect to tsuru server (), it's probably down

### ISSUE THREAD

**Issue by HudsonAfonso** [tsuru/tsuru#1490]
~ ⚡ $ tsuru-admin platform-add ruby -d https://raw.github.com/tsuru/basebuilder/master/ruby/Dockerfile
Error: Failed to connect to tsuru server (), it's probably down.

**Comment by fsouza** [comment]
That's a bug in tsuru-admin, you can't add a platform because you don't have a target defined, but tsuru-admin is lost. tsuru reacts properly, but tsuru-admin doesn't:

```
% tsuru app-list
Error: No target defined. Please use target-add/target-set to define a target.

For more details, please run "tsuru help target".
% tsuru-admin platform-add ruby
Error: Failed to connect to tsuru server (), it's probably down.
```

@HudsonAfonso you can check the list of available targets with the command `tsuru target-list``, and choose one using ``tsuru target-set``, ``tsuru help target`` will provide more information :)

**Comment by ArxdSilva** [comment]
Since no more info was given I'll keep this closed while the author does not get into it again.
