### ISSUE TITLE
Docker Volumes - how do they works?

### ISSUE THREAD

**Issue by guestisp** [tsuru/tsuru#2063]
As subject, how do they work? From docs, is not clear if Swarm or Kubernetes are needed as provisoner or if we can use plain docker

**Comment by magnotorres** [comment]
It will only work with Kubernetes and maybe Swarm for now.
We will deprecate Swarm unfortunately

[]s Magno
http://www.magnotorres.com.br
--

SHIFT ZZ

**Comment by guestisp** [comment]
I'm not interested in swarm, but in plain docker/docker-machine support.
Do you have plan to deprecate native docker support ?

**Comment by andrestc** [comment]
We have no plans to deprecate native docker support. On the other hand, we also have no plans to add more features to this provisioner as they would demand lots of work.

**Comment by guestisp** [comment]
> We have no plans to deprecate native docker support. On the other hand, we also have no plans to add more features to this provisioner as they would demand lots of work.

Sure, but supporting only kubernetes, makes tsuru much similiar to any other PaaS out there (openshift, deis, ...) and increase (a lot) the hardware requirements for a production environment (kuberneted, needs tons of servers/virtualmachines to do their best). Too many moving parts, IMHO

**Comment by andrestc** [comment]
Thats why we dont have plans to remove docker-cluster support.

But we also lack arms to be able to add more features to it. As an example, orchestrating volumes is hard and would require lots engineering effort to implement.

**Comment by fititnt** [comment]
@guestisp I was also concerned about the eventual risk of get no support for a Tsuru setup that could still work with smaller requirements, but to my surprise, maybe there is one alternative that still be possible and would be compatible with Kubernetes, the k3s <https://k3s.io/> (k8s - 5 = k3s)

With Kubernetes there is also a guide here https://github.com/hobby-kube/guide (TL;DR minimal setup 3 VPSs, 1GB RAM each). So in comparison to years ago, Kubernetes (even without k3s alternatives) seems to require less resource.

I'm citing Kubernetes in special in this issue you created because the solutions I'm finding more documentation on how to handle volumes (shared filesystems, snapshots, etc) tend to be more easy to find if using Kubernetes. Obviously it should still be possible to still use without this, using some sort of GlusterFS, Ceph, etc. I'm new to Tsuru, so I'm not sure how it was done in earlier days.

Maybe one alternative if focus now is more heavy on new features of Kubernetes, could be start some basics tests with k3s (or maybe what could come later that is compatible with kubernetes, or we just test on smaller nodes) so by the time the features of using direct the docker could become deprecated
