### ISSUE TITLE
ERROR during deploy: ---- Too many ports. You should especify which one you want to.

### ISSUE THREAD

**Issue by jhonyscamacho** [tsuru/tsuru#2074]
When i try to execute tsuru app-deploy -i kong -a kong-helloworld I get the following error:

```bash
Deploying image... ok
---- Getting process from image ----
---- Inspecting image "kong:latest" ----
---- ERROR during deploy: ----
Too many ports. You should especify which one you want to.
```

My team and i have been work in alternative solution: a custom Dockerfile to only export one port. 
Please take a llok at [https://github.com/cidac/kong-tsuru](https://github.com/cidac/kong-tsuru)

It would be nice if Tsuru accept the exposition of more than one port.

**Comment by guilhermebr** [comment]
@jhonyscamacho we accept more than one port when using kubernetes provisioner, because kubernetes already accept this. The docker provisioner is  in "maintenance-only mode," so we're not planning to add new features to it.

If using kubernetes, you can get more info here: https://docs.tsuru.io/stable/using/tsuru.yaml.html#kubernetes-specific-configs
