### ISSUE TITLE
Handling token while having multiple targets on tsuru-client

### ISSUE THREAD

**Issue by gfleury** [tsuru/tsuru#2088]
Hi, 

So, what are the best options to handle tokens for multiple targets on the client?

Is there any specific reason that the token file doesn't have one token per line like?

target1 token1
target2 token2

Plugins are injecting token/target before running, don't know if it would work. I'm also looking for something more plug'n'play like tsuru --target, or tsuru -t. 

Any insights on that?

**Comment by cezarsa** [comment]
I was thinking on something similar last week. Rather than multiple tokens in a single file I think it would be easier to manage having multiple token files, one for each target in `.tsuru/token.d/<target name>`.

To ease the migration process tsuru client could be changed to always look for the old `.tsuru/token` file if `.tsuru/token.d/<target name>` does not exist.

The second part of this change (changing the target for a single command or for a single shell instance) could be accomplished by changing how we handle the TSURU_TARGET environment variable.
Currently this environment variable must be a URL, we could change it to allow a target name. When selecting a target, tsuru would first list the existing targets from `.tsuru/targets` and if a target with name `$TSURU_TARGET` exists we would use it. If none exists we would fallback to the old behavior of using `$TSURU_TARGET` as a URL.

**Comment by gfleury** [comment]
Hi, 
First part, having it separated in directories, looking by how it is implemented now, is easier to do this way. 
Second part solve the problem and it's declarative, but can mess the head of guys that don't have a shell background, because then it's a mix of setting env vars and parameters. 

$ TSURU_TARGET=target1 tsuru app-log -a app1

This is very helpful for using it embedded on CI jobs/scripts or something similar, for daily use it is safe, can prevent acting on the wrong target. But I would say that something similar to, 

$ tsuru -target target1 app-log -a app1

is more easy to use and remember on a daily basis.

**Comment by cezarsa** [comment]
I agree, I think it would be nice to support `--target` argument in the tsuru command.

**Comment by gfleury** [comment]
So seems that we have the token management a bit spread among tsuru, tsuru-client and go-tsuruclient now.. ReadToken is implemented on all three places and writetoken is implemented on tsuru/tsuru. Is there some guideline on how to do it? is go-tsuruclient going to be the shared package between all other packages?

**Comment by cezarsa** [comment]
My idea is that we'll eventually remove the token management code from `tsuru/tsuru/cmd` and have it only in `go-tsuruclient`. I'll work on changing the cmd package do depend on it soon and remove all this duplicated code. For now there's no need to change it, I'll soon work on this refactor/integration.
