### ISSUE TITLE
router/hipache: use queue for removal operations

### ISSUE THREAD

**Issue by fsouza** [tsuru/tsuru#583]
If connection with Redis fail, the database may fall in an inconsistent state.

**Comment by andrewsmedina** [comment]
This issue is already fixed.

After a failure adding or removing routes from a router it was possible for applications to have incorrect route entries in the router. This happened because router failures generally also prevented rollback commands from successfully executing in the router. To prevent this problem from happening in the future tsuru will now check if the router is consistent after every operation that interacts with external routers. (app-deploy, app-swap, containers-move, healing process...)

If this check is not successful tsuru will schedule a message in it’s internal queue system (monsterqueue) that will keep trying to ensure routers are consistent. This should completely remove the possibility of having incorrect route entries after failures.
