### ISSUE TITLE
router: support tcp/udp applications

### ISSUE THREAD

**Issue by andrewsmedina** [tsuru/tsuru#983]
Currently tsuru has the hipache router that works for http/https applications.

The idea is to add router that support tcp/udp. There are some options like HAProxy that works fine for http/https and upd/tcp applications.

**Comment by cezarsa** [comment]
Back to brainstorm phase.

To support tcp/udp traffic we need a different IP per app. The initial idea was creating routers that would directly use either ELB for AWS deployments or Cloudstack Load Balancer API for Cloudstack deployments. 

The problem is, neither ELB nor Cloudstack allow creating a load balancer that would balance to the same backend IP but on different ports. This puts a stop on our plan of balancing directly to docker containers.

One possible idea about how to overcome this is to create new virtualmachines acting as load balancers, in a similar approach to how it's done in https://github.com/tsuru/rpaas. But the overhead would probably be too big, and it might lead to a vast amount of underused virtualmachines.

Any suggestions are welcome.

**Comment by robsonpeixoto** [comment]
Support to ELB or Cloudstack is really required? The HAProxy will help a lot.

**Comment by wpjunior** [comment]
Nowadays we achieved that using kubernetes external load balancer in kubernetes-router: https://github.com/tsuru/kubernetes-router.

Thanks
