### ISSUE TITLE
rebuilding routes

### ISSUE THREAD

**Issue by jblancett** [tsuru/tsuru#998]
There needs to be some way to regenerate routes/frontends in redis for hipache. Maybe a tsuru-admin command?  All the data is in mongodb so it should be fairly simple.
I can think of two good uses for this.

1) Disaster Recovery:  If you lose all your redis data for whatever reason, you could run this command and regenerate all the redis keys. 

2) If you change your hipache hostname, all current apps still use the old hostname.  This command could optionally update existing apps and then update the appropriate frontends in redis.  This would take a little more work than the previous example because the urls would need to be changed in mongodb before repopulating redis.

Maybe even add a flag to wipe redis first, which would probably be assumed in the second example

Thoughts?

**Comment by jblancett** [comment]
Bringing this back up since the addition of new router options makes it even more important.  Need a way to migrate if changing routers

**Comment by dcarley** [comment]
I've had a looked, with my limited understanding of the Tsuru codebase, at how the DR solution might be implemented. I'd appreciate your thoughts.

It seems like it could be done without modifying the router(s) by looping over `App.Units()` and using the existing `(Add|Remove)(Route|Backend)` methods to achieve consistency. This would mean that it'd work for all present and future routers. Although you wouldn't be able to identify/remove orphaned entries.

In which case I guess it would make sense to put this functionality in `App`, maybe as a `RebuildRoutes()` method, since it knows about each app's units and router. However `App` isn't currently responsible for adding/removing routes/backends for created/deleted units, it's the provisioner that does. Should `App` do that instead?

**Comment by cezarsa** [comment]
@dcarley You're right, calling router interface methods in the app package seems the cleanest way to go for this issue.
The reason the router is called by the provisioner today is because it's part of the deploy pipeline. This way, if adding new backends to the router fails for some reason, the pipeline will rollback the addition of new units and old units will remain working. I don't see a problem with both packages referencing the router.

**Comment by cezarsa** [comment]
Closed by tsuru/tsuru-admin@dea414ab6a7221733e71de57cd3f215d85c67576

**Comment by dcarley** [comment]
Thanks @cezarsa !

I got quite a long way into implementing this before realising that units didn't know about where the container is running, and then got horribly lost thinking about what bc6f586353358c9e8cdac03f8ddf3fd69caf5c95 now does :+1:
